package org.example.task_one;

public enum ViolationType {
    SPEEDING,
    ACDA,
    RED_TRAFFIC_LIGHT_DRIVING,
    PARKING_VIOLATION,
    SUSPENDED_LICENSE_DRIVING,
    CROSSWALK_STOP_FAILURE,
    STREET_RACING,
    RECKLESS_DRIVING,
    DRIVING_UNDER_INFLUENCE,
    SEATBELT_UNTIED,
    CARPOOL_LANE_VIOLATION,
    DISTRACTED_DRIVING,
    OFFENSIVE_BEHAVIOUR_TOWARDS_POLICE
}
